#!/usr/bin/ansible-playbook
---
- hosts: puppetmaster
  vars_files:
    - "vars/config.yml"
    - "vars/puppet_modules.yml"
  tasks:
    - include: tasks/add-puppetlabs-repo.yml
    - include: tasks/install-puppet-packages.yml
    - include: tasks/configure-puppetdb.yml
    - include: tasks/configure-hiera.yml
    - include: tasks/configure-puppetmaster.yml
    - include: tasks/load-puppet-modules.yml
    - include: tasks/initialize-puppet-services.yml
