---
- name: Place base epel yum repo file
  action: copy src=../files/epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Install the epel release package to get all the proper repos
  action: yum name=epel-release state=latest
