---
- name: Install all the puppet bits
  local_action: yum name=${item} state=installed
  with_items:
    - puppetlabs-release
    - puppet
    - puppet-server
    - puppetdb
    - puppetdb-terminus
    - facter
    - hiera
