this_playbook:
  repo: https://github.com/gregswift/ansible-puppetmaster
  dir: /etc/ansible/playbooks/puppetmaster
  version: master
inova:
puppetmaster:
  name: puppet.nytefyre.net
  type: existing
  flavor: 3
  image: blah
puppet_modules:
  prod:
    stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib
        version: 4.x
    role:
        repo: https://github.rackspace.com/cloud-integration-ops/ci-puppet-roles
        version: staging
    repo:
        repo: https://github.rackspace.com/cloud-integration-ops/puppet-repo
        version: master
        update: false
